name: DemoCraftMBwLayout
version: '${project.version}'
main: fr.democraft.democraftmbwlayout.DemoCraftMBwLayout
api-version: '1.13'
description: A MBedWars companion plugin that allow server admins to edit the position of the quickbuy button
author: Funasitien
website: https://f.drealclouds.fr
depend: [MBedwars, rustyconnector-paper]
